LOADER_OBJS += $(BUILD_DIR)/loader/$(ARCH)/boot.S.o
LOADER_OBJS += $(BUILD_DIR)/loader/$(ARCH)/allocator.c.o
LOADER_OBJS += $(BUILD_DIR)/loader/$(ARCH)/boot.c.o
LOADER_OBJS += $(BUILD_DIR)/loader/$(ARCH)/jitter.c.o
LOADER_OBJS += $(BUILD_DIR)/loader/$(ARCH)/paging.c.o
LOADER_OBJS += $(BUILD_DIR)/loader/$(ARCH)/log.c.o
LOADER_OBJS += $(BUILD_DIR)/loader/$(ARCH)/string.c.o
